"""
System Health Checker
---------------------
A simple IT support tool to quickly check the health of a Windows/Linux machine.
Useful for first-level diagnosis before escalating or opening a repair ticket.

Author: Gabriella Rodrigues Ormond
"""

import platform
import os
import shutil
import datetime

def get_disk_usage():
    total, used, free = shutil.disk_usage("/")
    total_gb = total // (2**30)
    used_gb = used // (2**30)
    free_gb = free // (2**30)
    percent_used = (used / total) * 100
    status = "WARNING - Low disk space!" if percent_used > 85 else "OK"
    return {
        "total": f"{total_gb} GB",
        "used": f"{used_gb} GB",
        "free": f"{free_gb} GB",
        "percent_used": f"{percent_used:.1f}%",
        "status": status
    }

def get_system_info():
    return {
        "os": platform.system(),
        "os_version": platform.version(),
        "machine": platform.machine(),
        "hostname": platform.node(),
        "processor": platform.processor()
    }

def get_uptime():
    # Works on Linux/Mac
    try:
        with open('/proc/uptime', 'r') as f:
            uptime_seconds = float(f.readline().split()[0])
            hours = int(uptime_seconds // 3600)
            minutes = int((uptime_seconds % 3600) // 60)
            return f"{hours}h {minutes}m"
    except FileNotFoundError:
        return "N/A (Windows - check Task Manager)"

def run_health_check():
    print("=" * 50)
    print("   SYSTEM HEALTH CHECK REPORT")
    print(f"   {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 50)

    print("\n[SYSTEM INFO]")
    info = get_system_info()
    for key, value in info.items():
        print(f"  {key.upper()}: {value}")

    print("\n[DISK USAGE]")
    disk = get_disk_usage()
    for key, value in disk.items():
        print(f"  {key.upper()}: {value}")

    print("\n[UPTIME]")
    print(f"  UPTIME: {get_uptime()}")

    print("\n[SUMMARY]")
    disk_ok = "OK" in get_disk_usage()["status"]
    if disk_ok:
        print("  All checks passed. System looks healthy.")
    else:
        print("  WARNING: Disk space is running low. Consider cleanup.")

    print("=" * 50)
    print("  Report generated by IT Support Tool v1.0")
    print("=" * 50)

if __name__ == "__main__":
    run_health_check()
